// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analysis_pmtiles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listAnalysisPmtilesByFieldID = `-- name: ListAnalysisPmtilesByFieldID :many
SELECT id, field_id, analysis_kind, analysis_date, module, pmtiles_url, created_at
FROM analysis_pmtiles_artifacts
WHERE field_id = $1
ORDER BY analysis_date DESC
`

func (q *Queries) ListAnalysisPmtilesByFieldID(ctx context.Context, fieldID uuid.UUID) ([]AnalysisPmtilesArtifact, error) {
	rows, err := q.db.Query(ctx, listAnalysisPmtilesByFieldID, fieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalysisPmtilesArtifact
	for rows.Next() {
		var i AnalysisPmtilesArtifact
		if err := rows.Scan(
			&i.ID,
			&i.FieldID,
			&i.AnalysisKind,
			&i.AnalysisDate,
			&i.Module,
			&i.PmtilesUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnalysisPmtilesArtifact = `-- name: UpsertAnalysisPmtilesArtifact :exec
INSERT INTO analysis_pmtiles_artifacts (field_id, analysis_kind, analysis_date, module, pmtiles_url)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (field_id, analysis_kind, analysis_date, module)
DO UPDATE SET pmtiles_url = EXCLUDED.pmtiles_url, created_at = now()
`

type UpsertAnalysisPmtilesArtifactParams struct {
	FieldID      uuid.UUID   `json:"field_id"`
	AnalysisKind string      `json:"analysis_kind"`
	AnalysisDate pgtype.Date `json:"analysis_date"`
	Module       string      `json:"module"`
	PmtilesUrl   string      `json:"pmtiles_url"`
}

func (q *Queries) UpsertAnalysisPmtilesArtifact(ctx context.Context, arg UpsertAnalysisPmtilesArtifactParams) error {
	_, err := q.db.Exec(ctx, upsertAnalysisPmtilesArtifact,
		arg.FieldID,
		arg.AnalysisKind,
		arg.AnalysisDate,
		arg.Module,
		arg.PmtilesUrl,
	)
	return err
}
