// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dashboard.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const orgDashboardStats = `-- name: OrgDashboardStats :one
WITH x AS (SELECT $1::uuid AS org_id)
SELECT
  (SELECT COUNT(*)::int FROM fields fi WHERE fi.organization_id = (SELECT org_id FROM x)) AS field_count,
  (SELECT COALESCE(SUM(fi.area_hectares), 0)::float8 FROM fields fi WHERE fi.organization_id = (SELECT org_id FROM x)) AS total_area_ha,
  (SELECT COUNT(DISTINCT fa.field_id)::int
   FROM field_analytics_timeseries fa
   INNER JOIN fields fi ON fi.id = fa.field_id AND fi.organization_id = (SELECT org_id FROM x)
   WHERE fa.source = 'observed'::analytics_source) AS fields_with_observed_analytics,
  (SELECT COUNT(*)::int FROM organization_members om WHERE om.organization_id = (SELECT org_id FROM x)) AS member_count
`

type OrgDashboardStatsRow struct {
	FieldCount                  int32   `json:"field_count"`
	TotalAreaHa                 float64 `json:"total_area_ha"`
	FieldsWithObservedAnalytics int32   `json:"fields_with_observed_analytics"`
	MemberCount                 int32   `json:"member_count"`
}

func (q *Queries) OrgDashboardStats(ctx context.Context, organizationID uuid.UUID) (OrgDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, orgDashboardStats, organizationID)
	var i OrgDashboardStatsRow
	err := row.Scan(
		&i.FieldCount,
		&i.TotalAreaHa,
		&i.FieldsWithObservedAnalytics,
		&i.MemberCount,
	)
	return i, err
}

const orgFieldsStaleProcessing = `-- name: OrgFieldsStaleProcessing :many
SELECT
  f.id,
  f.name,
  (
    SELECT MAX(fa.observation_date)::timestamptz
    FROM field_analytics_timeseries fa
    WHERE fa.field_id = f.id AND fa.source = 'observed'::analytics_source
  ) AS last_analytics_at,
  COALESCE((SELECT COUNT(*) FROM tiles t WHERE t.field_id = f.id), 0)::int AS tile_count
FROM fields f
WHERE f.organization_id = $1
  AND COALESCE((SELECT COUNT(*) FROM tiles t WHERE t.field_id = f.id), 0) > 0
  AND (
    NOT EXISTS (
      SELECT 1 FROM field_analytics_timeseries fa
      WHERE fa.field_id = f.id AND fa.source = 'observed'::analytics_source
    )
    OR (
      SELECT MAX(fa.observation_date)
      FROM field_analytics_timeseries fa
      WHERE fa.field_id = f.id AND fa.source = 'observed'::analytics_source
    ) < (now() AT TIME ZONE 'UTC') - interval '30 days'
  )
ORDER BY f.name
LIMIT $2
`

type OrgFieldsStaleProcessingParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	RowLimit       int32     `json:"row_limit"`
}

type OrgFieldsStaleProcessingRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	LastAnalyticsAt pgtype.Timestamptz `json:"last_analytics_at"`
	TileCount       int32              `json:"tile_count"`
}

func (q *Queries) OrgFieldsStaleProcessing(ctx context.Context, arg OrgFieldsStaleProcessingParams) ([]OrgFieldsStaleProcessingRow, error) {
	rows, err := q.db.Query(ctx, orgFieldsStaleProcessing, arg.OrganizationID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgFieldsStaleProcessingRow
	for rows.Next() {
		var i OrgFieldsStaleProcessingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LastAnalyticsAt,
			&i.TileCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgObservedNdviWeekly = `-- name: OrgObservedNdviWeekly :many
SELECT
  date_trunc('week', fa.observation_date AT TIME ZONE 'UTC')::timestamptz AS week_start,
  AVG(fa.ndvi_mean)::float8 AS ndvi_mean_avg
FROM field_analytics_timeseries fa
INNER JOIN fields f ON f.id = fa.field_id AND f.organization_id = $1
WHERE fa.source = 'observed'::analytics_source
  AND fa.ndvi_mean IS NOT NULL
  AND fa.observation_date >= (now() AT TIME ZONE 'UTC') - interval '8 weeks'
GROUP BY 1
ORDER BY 1 ASC
`

type OrgObservedNdviWeeklyRow struct {
	WeekStart   pgtype.Timestamptz `json:"week_start"`
	NdviMeanAvg float64            `json:"ndvi_mean_avg"`
}

func (q *Queries) OrgObservedNdviWeekly(ctx context.Context, organizationID uuid.UUID) ([]OrgObservedNdviWeeklyRow, error) {
	rows, err := q.db.Query(ctx, orgObservedNdviWeekly, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgObservedNdviWeeklyRow
	for rows.Next() {
		var i OrgObservedNdviWeeklyRow
		if err := rows.Scan(&i.WeekStart, &i.NdviMeanAvg); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
