// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: field_audit.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertFieldAuditLog = `-- name: InsertFieldAuditLog :exec
INSERT INTO field_audit_log (id, field_id, actor_user_id, action, payload, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, now())
`

type InsertFieldAuditLogParams struct {
	FieldID     uuid.UUID `json:"field_id"`
	ActorUserID uuid.UUID `json:"actor_user_id"`
	Action      string    `json:"action"`
	Payload     []byte    `json:"payload"`
}

func (q *Queries) InsertFieldAuditLog(ctx context.Context, arg InsertFieldAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertFieldAuditLog,
		arg.FieldID,
		arg.ActorUserID,
		arg.Action,
		arg.Payload,
	)
	return err
}

const listFieldAuditLogByFieldID = `-- name: ListFieldAuditLogByFieldID :many
SELECT id, field_id, actor_user_id, action, payload, created_at
FROM field_audit_log
WHERE field_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListFieldAuditLogByFieldIDParams struct {
	FieldID  uuid.UUID `json:"field_id"`
	RowLimit int32     `json:"row_limit"`
}

func (q *Queries) ListFieldAuditLogByFieldID(ctx context.Context, arg ListFieldAuditLogByFieldIDParams) ([]FieldAuditLog, error) {
	rows, err := q.db.Query(ctx, listFieldAuditLogByFieldID, arg.FieldID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FieldAuditLog
	for rows.Next() {
		var i FieldAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.FieldID,
			&i.ActorUserID,
			&i.Action,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldAuditLogByOrganizationID = `-- name: ListFieldAuditLogByOrganizationID :many
SELECT
  a.id,
  a.field_id,
  a.actor_user_id,
  a.action,
  a.payload,
  a.created_at,
  f.name AS field_name
FROM field_audit_log a
INNER JOIN fields f ON f.id = a.field_id AND f.organization_id = $1
ORDER BY a.created_at DESC
LIMIT $2
`

type ListFieldAuditLogByOrganizationIDParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	RowLimit       int32     `json:"row_limit"`
}

type ListFieldAuditLogByOrganizationIDRow struct {
	ID          uuid.UUID          `json:"id"`
	FieldID     uuid.UUID          `json:"field_id"`
	ActorUserID uuid.UUID          `json:"actor_user_id"`
	Action      string             `json:"action"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	FieldName   string             `json:"field_name"`
}

func (q *Queries) ListFieldAuditLogByOrganizationID(ctx context.Context, arg ListFieldAuditLogByOrganizationIDParams) ([]ListFieldAuditLogByOrganizationIDRow, error) {
	rows, err := q.db.Query(ctx, listFieldAuditLogByOrganizationID, arg.OrganizationID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFieldAuditLogByOrganizationIDRow
	for rows.Next() {
		var i ListFieldAuditLogByOrganizationIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FieldID,
			&i.ActorUserID,
			&i.Action,
			&i.Payload,
			&i.CreatedAt,
			&i.FieldName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
