// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: field.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createField = `-- name: CreateField :one
INSERT INTO fields (
  id,
  name,
  description,
  geometry,
  organization_id
)
VALUES (
  $1,
  $2,
  $3,
  ST_GeomFromWKB($4::bytea, 4326),
  $5
)
RETURNING id
`

type CreateFieldParams struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	GeometryWkb    []byte      `json:"geometry_wkb"`
	OrganizationID uuid.UUID   `json:"organization_id"`
}

func (q *Queries) CreateField(ctx context.Context, arg CreateFieldParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createField,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.GeometryWkb,
		arg.OrganizationID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteField = `-- name: DeleteField :exec
DELETE FROM fields WHERE id = $1
`

func (q *Queries) DeleteField(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteField, id)
	return err
}

const getFieldByID = `-- name: GetFieldByID :one
SELECT id, name, description, created_at, ST_AsBinary(geometry)::bytea AS geometry_wkb, area_hectares, organization_id
FROM fields
WHERE id = $1
`

type GetFieldByIDRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	GeometryWkb    []byte             `json:"geometry_wkb"`
	AreaHectares   pgtype.Numeric     `json:"area_hectares"`
	OrganizationID uuid.UUID          `json:"organization_id"`
}

func (q *Queries) GetFieldByID(ctx context.Context, id uuid.UUID) (GetFieldByIDRow, error) {
	row := q.db.QueryRow(ctx, getFieldByID, id)
	var i GetFieldByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.GeometryWkb,
		&i.AreaHectares,
		&i.OrganizationID,
	)
	return i, err
}

const listFieldsByOrganizationID = `-- name: ListFieldsByOrganizationID :many
SELECT id, name, description, created_at, ST_AsBinary(geometry)::bytea AS geometry_wkb, area_hectares, organization_id
FROM fields
WHERE organization_id = $1
ORDER BY created_at DESC
`

type ListFieldsByOrganizationIDRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	GeometryWkb    []byte             `json:"geometry_wkb"`
	AreaHectares   pgtype.Numeric     `json:"area_hectares"`
	OrganizationID uuid.UUID          `json:"organization_id"`
}

func (q *Queries) ListFieldsByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]ListFieldsByOrganizationIDRow, error) {
	rows, err := q.db.Query(ctx, listFieldsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFieldsByOrganizationIDRow
	for rows.Next() {
		var i ListFieldsByOrganizationIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.GeometryWkb,
			&i.AreaHectares,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateField = `-- name: UpdateField :exec
UPDATE fields
SET name = $1, description = $2
WHERE id = $3
`

type UpdateFieldParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateField(ctx context.Context, arg UpdateFieldParams) error {
	_, err := q.db.Exec(ctx, updateField, arg.Name, arg.Description, arg.ID)
	return err
}
