// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: field.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createField = `-- name: CreateField :one
INSERT INTO fields (
  id,
  name,
  description,
  geometry,
  organization_id
)
VALUES (
  $1,
  $2,
  $3,
  ST_GeomFromWKB($4::bytea, 4326),
  $5
)
RETURNING id
`

type CreateFieldParams struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	GeometryWkb    []byte      `json:"geometry_wkb"`
	OrganizationID uuid.UUID   `json:"organization_id"`
}

func (q *Queries) CreateField(ctx context.Context, arg CreateFieldParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createField,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.GeometryWkb,
		arg.OrganizationID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteField = `-- name: DeleteField :exec
DELETE FROM fields WHERE id = $1
`

func (q *Queries) DeleteField(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteField, id)
	return err
}

const getFieldByID = `-- name: GetFieldByID :one
SELECT id, name, description, created_at, ST_AsBinary(geometry)::bytea AS geometry_wkb, area_hectares, organization_id
FROM fields
WHERE id = $1
`

type GetFieldByIDRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	GeometryWkb    []byte             `json:"geometry_wkb"`
	AreaHectares   pgtype.Numeric     `json:"area_hectares"`
	OrganizationID uuid.UUID          `json:"organization_id"`
}

func (q *Queries) GetFieldByID(ctx context.Context, id uuid.UUID) (GetFieldByIDRow, error) {
	row := q.db.QueryRow(ctx, getFieldByID, id)
	var i GetFieldByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.GeometryWkb,
		&i.AreaHectares,
		&i.OrganizationID,
	)
	return i, err
}

const listFieldsByOrganizationID = `-- name: ListFieldsByOrganizationID :many
SELECT
  f.id,
  f.name,
  f.description,
  f.created_at,
  ST_AsBinary(f.geometry)::bytea AS geometry_wkb,
  f.area_hectares,
  f.organization_id,
  COALESCE((SELECT COUNT(*) FROM tiles t WHERE t.field_id = f.id), 0)::int AS tile_count,
  COALESCE((SELECT COUNT(*) FROM seasons s WHERE s.field_id = f.id), 0)::int AS season_count,
  (SELECT MAX(tt.observation_date) FROM tile_timeseries tt
    INNER JOIN tiles t ON t.id = tt.tile_id AND t.field_id = f.id)::timestamptz AS latest_observation_at,
  COALESCE((
    SELECT COUNT(DISTINCT fa.observation_date)
    FROM field_analytics_timeseries fa
    WHERE fa.field_id = f.id AND fa.source = 'observed'::analytics_source
  ), 0)::int AS observed_analytics_dates,
  COALESCE((SELECT COUNT(*) FROM analysis_pmtiles_artifacts apa WHERE apa.field_id = f.id), 0)::int AS pmtiles_layer_count
FROM fields f
WHERE f.organization_id = $1
ORDER BY f.created_at DESC
`

type ListFieldsByOrganizationIDRow struct {
	ID                     uuid.UUID          `json:"id"`
	Name                   string             `json:"name"`
	Description            pgtype.Text        `json:"description"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	GeometryWkb            []byte             `json:"geometry_wkb"`
	AreaHectares           pgtype.Numeric     `json:"area_hectares"`
	OrganizationID         uuid.UUID          `json:"organization_id"`
	TileCount              int32              `json:"tile_count"`
	SeasonCount            int32              `json:"season_count"`
	LatestObservationAt    pgtype.Timestamptz `json:"latest_observation_at"`
	ObservedAnalyticsDates int32              `json:"observed_analytics_dates"`
	PmtilesLayerCount      int32              `json:"pmtiles_layer_count"`
}

func (q *Queries) ListFieldsByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]ListFieldsByOrganizationIDRow, error) {
	rows, err := q.db.Query(ctx, listFieldsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFieldsByOrganizationIDRow
	for rows.Next() {
		var i ListFieldsByOrganizationIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.GeometryWkb,
			&i.AreaHectares,
			&i.OrganizationID,
			&i.TileCount,
			&i.SeasonCount,
			&i.LatestObservationAt,
			&i.ObservedAnalyticsDates,
			&i.PmtilesLayerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateField = `-- name: UpdateField :exec
UPDATE fields
SET name = $1, description = $2
WHERE id = $3
`

type UpdateFieldParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateField(ctx context.Context, arg UpdateFieldParams) error {
	_, err := q.db.Exec(ctx, updateField, arg.Name, arg.Description, arg.ID)
	return err
}
