// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/twpayne/go-geom"
)

type AlertLevel string

const (
	AlertLevelNone     AlertLevel = "none"
	AlertLevelLow      AlertLevel = "low"
	AlertLevelMedium   AlertLevel = "medium"
	AlertLevelHigh     AlertLevel = "high"
	AlertLevelCritical AlertLevel = "critical"
)

func (e *AlertLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertLevel(s)
	case string:
		*e = AlertLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertLevel: %T", src)
	}
	return nil
}

type NullAlertLevel struct {
	AlertLevel AlertLevel `json:"alert_level"`
	Valid      bool       `json:"valid"` // Valid is true if AlertLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertLevel) Scan(value interface{}) error {
	if value == nil {
		ns.AlertLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertLevel), nil
}

type AnalyticsSource string

const (
	AnalyticsSourceObserved  AnalyticsSource = "observed"
	AnalyticsSourceDerived   AnalyticsSource = "derived"
	AnalyticsSourcePredicted AnalyticsSource = "predicted"
)

func (e *AnalyticsSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnalyticsSource(s)
	case string:
		*e = AnalyticsSource(s)
	default:
		return fmt.Errorf("unsupported scan type for AnalyticsSource: %T", src)
	}
	return nil
}

type NullAnalyticsSource struct {
	AnalyticsSource AnalyticsSource `json:"analytics_source"`
	Valid           bool            `json:"valid"` // Valid is true if AnalyticsSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnalyticsSource) Scan(value interface{}) error {
	if value == nil {
		ns.AnalyticsSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnalyticsSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnalyticsSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnalyticsSource), nil
}

type DegradationLevel string

const (
	DegradationLevelNone   DegradationLevel = "none"
	DegradationLevelLow    DegradationLevel = "low"
	DegradationLevelMedium DegradationLevel = "medium"
	DegradationLevelHigh   DegradationLevel = "high"
	DegradationLevelSevere DegradationLevel = "severe"
)

func (e *DegradationLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DegradationLevel(s)
	case string:
		*e = DegradationLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for DegradationLevel: %T", src)
	}
	return nil
}

type NullDegradationLevel struct {
	DegradationLevel DegradationLevel `json:"degradation_level"`
	Valid            bool             `json:"valid"` // Valid is true if DegradationLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDegradationLevel) Scan(value interface{}) error {
	if value == nil {
		ns.DegradationLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DegradationLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDegradationLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DegradationLevel), nil
}

type PredictionModule string

const (
	PredictionModuleHealthStress       PredictionModule = "health_stress"
	PredictionModuleIrrigationWaterUse PredictionModule = "irrigation_water_use"
	PredictionModuleDegradation        PredictionModule = "degradation"
)

func (e *PredictionModule) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PredictionModule(s)
	case string:
		*e = PredictionModule(s)
	default:
		return fmt.Errorf("unsupported scan type for PredictionModule: %T", src)
	}
	return nil
}

type NullPredictionModule struct {
	PredictionModule PredictionModule `json:"prediction_module"`
	Valid            bool             `json:"valid"` // Valid is true if PredictionModule is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPredictionModule) Scan(value interface{}) error {
	if value == nil {
		ns.PredictionModule, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PredictionModule.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPredictionModule) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PredictionModule), nil
}

type PredictionStatus string

const (
	PredictionStatusInProgress PredictionStatus = "in_progress"
	PredictionStatusCompleted  PredictionStatus = "completed"
	PredictionStatusFailed     PredictionStatus = "failed"
)

func (e *PredictionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PredictionStatus(s)
	case string:
		*e = PredictionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PredictionStatus: %T", src)
	}
	return nil
}

type NullPredictionStatus struct {
	PredictionStatus PredictionStatus `json:"prediction_status"`
	Valid            bool             `json:"valid"` // Valid is true if PredictionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPredictionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PredictionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PredictionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPredictionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PredictionStatus), nil
}

type TrendDirection string

const (
	TrendDirectionImproving TrendDirection = "improving"
	TrendDirectionStable    TrendDirection = "stable"
	TrendDirectionWorsening TrendDirection = "worsening"
)

func (e *TrendDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrendDirection(s)
	case string:
		*e = TrendDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for TrendDirection: %T", src)
	}
	return nil
}

type NullTrendDirection struct {
	TrendDirection TrendDirection `json:"trend_direction"`
	Valid          bool           `json:"valid"` // Valid is true if TrendDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrendDirection) Scan(value interface{}) error {
	if value == nil {
		ns.TrendDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrendDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrendDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrendDirection), nil
}

type UserRole string

const (
	UserRoleAdmin   UserRole = "admin"
	UserRoleManager UserRole = "manager"
	UserRoleFarmer  UserRole = "farmer"
	UserRoleViewer  UserRole = "viewer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type WaterBalanceStatus string

const (
	WaterBalanceStatusBalanced       WaterBalanceStatus = "balanced"
	WaterBalanceStatusUnderIrrigated WaterBalanceStatus = "under_irrigated"
	WaterBalanceStatusOverIrrigated  WaterBalanceStatus = "over_irrigated"
	WaterBalanceStatusUnknown        WaterBalanceStatus = "unknown"
)

func (e *WaterBalanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WaterBalanceStatus(s)
	case string:
		*e = WaterBalanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WaterBalanceStatus: %T", src)
	}
	return nil
}

type NullWaterBalanceStatus struct {
	WaterBalanceStatus WaterBalanceStatus `json:"water_balance_status"`
	Valid              bool               `json:"valid"` // Valid is true if WaterBalanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWaterBalanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WaterBalanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WaterBalanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWaterBalanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WaterBalanceStatus), nil
}

type AnalysisPmtilesArtifact struct {
	ID           uuid.UUID          `json:"id"`
	FieldID      uuid.UUID          `json:"field_id"`
	AnalysisKind string             `json:"analysis_kind"`
	AnalysisDate pgtype.Date        `json:"analysis_date"`
	Module       string             `json:"module"`
	PmtilesUrl   string             `json:"pmtiles_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Field struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Geometry       geom.Polygon       `json:"geometry"`
	AreaHectares   pgtype.Numeric     `json:"area_hectares"`
	OrganizationID uuid.UUID          `json:"organization_id"`
}

type FieldAnalyticsTimeseries struct {
	ID                                 uuid.UUID          `json:"id"`
	FieldID                            uuid.UUID          `json:"field_id"`
	ObservationDate                    pgtype.Timestamptz `json:"observation_date"`
	Source                             AnalyticsSource    `json:"source"`
	TileCount                          pgtype.Int4        `json:"tile_count"`
	ValidTileCount                     pgtype.Int4        `json:"valid_tile_count"`
	VhMean                             pgtype.Numeric     `json:"vh_mean"`
	VvMean                             pgtype.Numeric     `json:"vv_mean"`
	Nbr2Mean                           pgtype.Numeric     `json:"nbr2_mean"`
	NdmiMean                           pgtype.Numeric     `json:"ndmi_mean"`
	NdreMean                           pgtype.Numeric     `json:"ndre_mean"`
	NdviMean                           pgtype.Numeric     `json:"ndvi_mean"`
	GndviMean                          pgtype.Numeric     `json:"gndvi_mean"`
	MsaviMean                          pgtype.Numeric     `json:"msavi_mean"`
	DryDaysMean                        pgtype.Numeric     `json:"dry_days_mean"`
	BareSoilIndexMean                  pgtype.Numeric     `json:"bare_soil_index_mean"`
	ValidPixelRatioMean                pgtype.Numeric     `json:"valid_pixel_ratio_mean"`
	TemperatureCMean                   pgtype.Numeric     `json:"temperature_c_mean"`
	PrecipitationMm3dMean              pgtype.Numeric     `json:"precipitation_mm_3d_mean"`
	PrecipitationMm7dMean              pgtype.Numeric     `json:"precipitation_mm_7d_mean"`
	PrecipitationMm30dMean             pgtype.Numeric     `json:"precipitation_mm_30d_mean"`
	StressIndexMean                    pgtype.Numeric     `json:"stress_index_mean"`
	StressIndexP25                     pgtype.Numeric     `json:"stress_index_p25"`
	StressIndexP50                     pgtype.Numeric     `json:"stress_index_p50"`
	StressIndexP75                     pgtype.Numeric     `json:"stress_index_p75"`
	StressIndexStddev                  pgtype.Numeric     `json:"stress_index_stddev"`
	NdviStddev                         pgtype.Numeric     `json:"ndvi_stddev"`
	NdmiStddev                         pgtype.Numeric     `json:"ndmi_stddev"`
	NdreStddev                         pgtype.Numeric     `json:"ndre_stddev"`
	HeterogeneityScore                 pgtype.Numeric     `json:"heterogeneity_score"`
	PredictionDegradationScore         pgtype.Numeric     `json:"prediction_degradation_score"`
	PredictionVegetationCoverLossScore pgtype.Numeric     `json:"prediction_vegetation_cover_loss_score"`
	PredictionBareSoilExpansionScore   pgtype.Numeric     `json:"prediction_bare_soil_expansion_score"`
	PredictionHealthScore              pgtype.Numeric     `json:"prediction_health_score"`
	PredictionStressScoreTotal         pgtype.Numeric     `json:"prediction_stress_score_total"`
	PredictionWaterStress              pgtype.Numeric     `json:"prediction_water_stress"`
	PredictionConfidence               pgtype.Numeric     `json:"prediction_confidence"`
	PredictionUnderIrrigationRiskScore pgtype.Numeric     `json:"prediction_under_irrigation_risk_score"`
	PredictionOverIrrigationRiskScore  pgtype.Numeric     `json:"prediction_over_irrigation_risk_score"`
	PredictionUniformityScore          pgtype.Numeric     `json:"prediction_uniformity_score"`
	PredictionVegetationActivityDrop   pgtype.Numeric     `json:"prediction_vegetation_activity_drop"`
	PredictionHeterogeneityGrowth      pgtype.Numeric     `json:"prediction_heterogeneity_growth"`
	PredictionIrrigationEventsDetected pgtype.Numeric     `json:"prediction_irrigation_events_detected"`
	CreatedAt                          pgtype.Timestamptz `json:"created_at"`
}

type FieldPrediction struct {
	ID             uuid.UUID          `json:"id"`
	FieldID        uuid.UUID          `json:"field_id"`
	Module         PredictionModule   `json:"module"`
	PredictionDate pgtype.Timestamptz `json:"prediction_date"`
	Status         PredictionStatus   `json:"status"`
	ModelVersion   pgtype.Text        `json:"model_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type FieldPredictionsDegradation struct {
	ID                       uuid.UUID            `json:"id"`
	DegradationScore         pgtype.Numeric       `json:"degradation_score"`
	DegradationLevel         NullDegradationLevel `json:"degradation_level"`
	Trend                    NullTrendDirection   `json:"trend"`
	VegetationCoverLossScore pgtype.Numeric       `json:"vegetation_cover_loss_score"`
	BareSoilExpansionScore   pgtype.Numeric       `json:"bare_soil_expansion_score"`
	HeterogeneityScore       pgtype.Numeric       `json:"heterogeneity_score"`
	AlertLevel               NullAlertLevel       `json:"alert_level"`
	AffectedTileRatio        pgtype.Numeric       `json:"affected_tile_ratio"`
	Explanations             []byte               `json:"explanations"`
}

type FieldPredictionsHealthStress struct {
	ID                     uuid.UUID          `json:"id"`
	HealthScore            pgtype.Numeric     `json:"health_score"`
	StressScoreTotal       pgtype.Numeric     `json:"stress_score_total"`
	WaterStress            pgtype.Numeric     `json:"water_stress"`
	VegetationActivityDrop pgtype.Numeric     `json:"vegetation_activity_drop"`
	HeterogeneityGrowth    pgtype.Numeric     `json:"heterogeneity_growth"`
	AlertLevel             NullAlertLevel     `json:"alert_level"`
	Trend                  NullTrendDirection `json:"trend"`
	AffectedTileRatio      pgtype.Numeric     `json:"affected_tile_ratio"`
	Explanations           []byte             `json:"explanations"`
}

type FieldPredictionsIrrigationWaterUse struct {
	ID                       uuid.UUID              `json:"id"`
	IsIrrigated              pgtype.Bool            `json:"is_irrigated"`
	Confidence               pgtype.Numeric         `json:"confidence"`
	WaterBalanceStatus       NullWaterBalanceStatus `json:"water_balance_status"`
	UnderIrrigationRiskScore pgtype.Numeric         `json:"under_irrigation_risk_score"`
	OverIrrigationRiskScore  pgtype.Numeric         `json:"over_irrigation_risk_score"`
	UniformityScore          pgtype.Numeric         `json:"uniformity_score"`
	AffectedTileRatio        pgtype.Numeric         `json:"affected_tile_ratio"`
	Explanations             []byte                 `json:"explanations"`
}

type Organization struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy uuid.UUID          `json:"created_by"`
}

type OrganizationMember struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Role           UserRole           `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Outbox struct {
	ID             uuid.UUID          `json:"id"`
	AggregateType  pgtype.Text        `json:"aggregate_type"`
	AggregateID    pgtype.UUID        `json:"aggregate_id"`
	MessageType    pgtype.Text        `json:"message_type"`
	MessagePayload []byte             `json:"message_payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	RetryCount     int32              `json:"retry_count"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	Status         pgtype.Text        `json:"status"`
}

type Season struct {
	ID        uuid.UUID          `json:"id"`
	FieldID   uuid.UUID          `json:"field_id"`
	Name      string             `json:"name"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	IsAuto    bool               `json:"is_auto"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tile struct {
	ID       uuid.UUID    `json:"id"`
	FieldID  uuid.UUID    `json:"field_id"`
	Geometry geom.Polygon `json:"geometry"`
}

type TilePrediction struct {
	ID             uuid.UUID          `json:"id"`
	TileID         uuid.UUID          `json:"tile_id"`
	Module         PredictionModule   `json:"module"`
	PredictionDate pgtype.Timestamptz `json:"prediction_date"`
	Status         PredictionStatus   `json:"status"`
	ModelVersion   pgtype.Text        `json:"model_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type TilePredictionsDegradation struct {
	ID                       uuid.UUID            `json:"id"`
	DegradationScore         pgtype.Numeric       `json:"degradation_score"`
	DegradationLevel         NullDegradationLevel `json:"degradation_level"`
	Trend                    NullTrendDirection   `json:"trend"`
	VegetationCoverLossScore pgtype.Numeric       `json:"vegetation_cover_loss_score"`
	BareSoilExpansionScore   pgtype.Numeric       `json:"bare_soil_expansion_score"`
	HeterogeneityScore       pgtype.Numeric       `json:"heterogeneity_score"`
	AlertLevel               NullAlertLevel       `json:"alert_level"`
	Explanations             []byte               `json:"explanations"`
}

type TilePredictionsHealthStress struct {
	ID                     uuid.UUID          `json:"id"`
	HealthScore            pgtype.Numeric     `json:"health_score"`
	StressScoreTotal       pgtype.Numeric     `json:"stress_score_total"`
	WaterStress            pgtype.Numeric     `json:"water_stress"`
	VegetationActivityDrop pgtype.Numeric     `json:"vegetation_activity_drop"`
	HeterogeneityGrowth    pgtype.Numeric     `json:"heterogeneity_growth"`
	AlertLevel             NullAlertLevel     `json:"alert_level"`
	Trend                  NullTrendDirection `json:"trend"`
	Explanations           []byte             `json:"explanations"`
}

type TilePredictionsIrrigationWaterUse struct {
	ID                       uuid.UUID              `json:"id"`
	IsIrrigated              pgtype.Bool            `json:"is_irrigated"`
	Confidence               pgtype.Numeric         `json:"confidence"`
	WaterBalanceStatus       NullWaterBalanceStatus `json:"water_balance_status"`
	UnderIrrigationRiskScore pgtype.Numeric         `json:"under_irrigation_risk_score"`
	OverIrrigationRiskScore  pgtype.Numeric         `json:"over_irrigation_risk_score"`
	UniformityScore          pgtype.Numeric         `json:"uniformity_score"`
	Explanations             []byte                 `json:"explanations"`
}

type TileTimeseries struct {
	ID                 uuid.UUID          `json:"id"`
	TileID             uuid.UUID          `json:"tile_id"`
	ObservationDate    pgtype.Timestamptz `json:"observation_date"`
	Vh                 pgtype.Numeric     `json:"vh"`
	Vv                 pgtype.Numeric     `json:"vv"`
	Nbr2               pgtype.Numeric     `json:"nbr2"`
	Ndmi               pgtype.Numeric     `json:"ndmi"`
	Ndre               pgtype.Numeric     `json:"ndre"`
	Ndvi               pgtype.Numeric     `json:"ndvi"`
	Gndvi              pgtype.Numeric     `json:"gndvi"`
	Msavi              pgtype.Numeric     `json:"msavi"`
	DryDays            pgtype.Int4        `json:"dry_days"`
	BareSoilIndex      pgtype.Numeric     `json:"bare_soil_index"`
	ValidPixelRatio    pgtype.Numeric     `json:"valid_pixel_ratio"`
	TemperatureCMean   pgtype.Numeric     `json:"temperature_c_mean"`
	PrecipitationMm3d  pgtype.Numeric     `json:"precipitation_mm_3d"`
	PrecipitationMm7d  pgtype.Numeric     `json:"precipitation_mm_7d"`
	PrecipitationMm30d pgtype.Numeric     `json:"precipitation_mm_30d"`
	StressIndex        pgtype.Numeric     `json:"stress_index"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
}
