// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: organization.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations(
  id,
  name,
  created_at,
  created_by
) VALUES($1,$2,$3,$4) RETURNING id
`

type CreateOrganizationParams struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy uuid.UUID          `json:"created_by"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const inviteMemberToOrganization = `-- name: InviteMemberToOrganization :exec
INSERT INTO organization_members(
  organization_id,
  user_id,
  role,
  created_at
) VALUES($1,$2,$3,$4)
`

type InviteMemberToOrganizationParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Role           UserRole           `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InviteMemberToOrganization(ctx context.Context, arg InviteMemberToOrganizationParams) error {
	_, err := q.db.Exec(ctx, inviteMemberToOrganization,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const listOrganizationsForUser = `-- name: ListOrganizationsForUser :many
SELECT o.id, o.name
FROM organizations o
WHERE o.created_by = $1
   OR EXISTS (
     SELECT 1 FROM organization_members m
     WHERE m.organization_id = o.id AND m.user_id = $1
   )
ORDER BY o.name
`

type ListOrganizationsForUserRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ListOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]ListOrganizationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationsForUserRow
	for rows.Next() {
		var i ListOrganizationsForUserRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
