// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: outbox.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimOneEvent = `-- name: ClaimOneEvent :one
UPDATE outbox
SET status = 'processing'
WHERE id = (
    SELECT id
    FROM outbox
    WHERE status = 'pending' AND next_attempt_at <= now() AND retry_count < 3
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, aggregate_type, aggregate_id, message_type, message_payload, created_at, status, retry_count
`

type ClaimOneEventRow struct {
	ID             uuid.UUID          `json:"id"`
	AggregateType  pgtype.Text        `json:"aggregate_type"`
	AggregateID    pgtype.UUID        `json:"aggregate_id"`
	MessageType    pgtype.Text        `json:"message_type"`
	MessagePayload []byte             `json:"message_payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Status         pgtype.Text        `json:"status"`
	RetryCount     int32              `json:"retry_count"`
}

func (q *Queries) ClaimOneEvent(ctx context.Context) (ClaimOneEventRow, error) {
	row := q.db.QueryRow(ctx, claimOneEvent)
	var i ClaimOneEventRow
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.MessageType,
		&i.MessagePayload,
		&i.CreatedAt,
		&i.Status,
		&i.RetryCount,
	)
	return i, err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox(id, aggregate_type, aggregate_id, message_type, message_payload, created_at, status)
VALUES($1,$2,$3,$4,$5,$6, $7)
`

type CreateOutboxEventParams struct {
	ID             uuid.UUID          `json:"id"`
	AggregateType  pgtype.Text        `json:"aggregate_type"`
	AggregateID    pgtype.UUID        `json:"aggregate_id"`
	MessageType    pgtype.Text        `json:"message_type"`
	MessagePayload []byte             `json:"message_payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Status         pgtype.Text        `json:"status"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.MessageType,
		arg.MessagePayload,
		arg.CreatedAt,
		arg.Status,
	)
	return err
}

const markFailed = `-- name: MarkFailed :exec
UPDATE outbox
SET
status = 'pending',
next_attempt_at = now() + interval '30 seconds',
retry_count = retry_count + 1
WHERE id = $1 AND status = 'processing'
`

func (q *Queries) MarkFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markFailed, id)
	return err
}

const markSent = `-- name: MarkSent :exec
UPDATE outbox
SET
status = 'sent',
processed_at = now()
WHERE id = $1 AND status = 'processing'
`

func (q *Queries) MarkSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSent, id)
	return err
}
