// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: season.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSeason = `-- name: CreateSeason :one
INSERT INTO seasons (id, field_id, name, start_date, end_date, is_auto)
VALUES (
  gen_random_uuid(),
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id
`

type CreateSeasonParams struct {
	FieldID   uuid.UUID   `json:"field_id"`
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	IsAuto    bool        `json:"is_auto"`
}

func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSeason,
		arg.FieldID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.IsAuto,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteSeason = `-- name: DeleteSeason :exec
DELETE FROM seasons WHERE id = $1
`

func (q *Queries) DeleteSeason(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSeason, id)
	return err
}

const getSeasonByID = `-- name: GetSeasonByID :one
SELECT id, field_id, name, start_date, end_date, is_auto, created_at
FROM seasons
WHERE id = $1
`

func (q *Queries) GetSeasonByID(ctx context.Context, id uuid.UUID) (Season, error) {
	row := q.db.QueryRow(ctx, getSeasonByID, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.FieldID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.IsAuto,
		&i.CreatedAt,
	)
	return i, err
}

const listSeasonsByFieldID = `-- name: ListSeasonsByFieldID :many
SELECT id, field_id, name, start_date, end_date, is_auto, created_at
FROM seasons
WHERE field_id = $1
ORDER BY start_date DESC
`

func (q *Queries) ListSeasonsByFieldID(ctx context.Context, fieldID uuid.UUID) ([]Season, error) {
	rows, err := q.db.Query(ctx, listSeasonsByFieldID, fieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.FieldID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.IsAuto,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeason = `-- name: UpdateSeason :exec
UPDATE seasons
SET name = $1, start_date = $2, end_date = $3, is_auto = $4
WHERE id = $5
`

type UpdateSeasonParams struct {
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	IsAuto    bool        `json:"is_auto"`
	ID        uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateSeason(ctx context.Context, arg UpdateSeasonParams) error {
	_, err := q.db.Exec(ctx, updateSeason,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.IsAuto,
		arg.ID,
	)
	return err
}
