// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tile_timeseries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMaxObservationDateForField = `-- name: GetMaxObservationDateForField :one
SELECT MAX(tt.observation_date)::timestamptz AS max_date
FROM tile_timeseries tt
JOIN tiles t ON t.id = tt.tile_id
WHERE t.field_id = $1
`

func (q *Queries) GetMaxObservationDateForField(ctx context.Context, fieldID uuid.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getMaxObservationDateForField, fieldID)
	var max_date pgtype.Timestamptz
	err := row.Scan(&max_date)
	return max_date, err
}

const insertTileTimeseries = `-- name: InsertTileTimeseries :one
INSERT INTO tile_timeseries (
  id, tile_id, observation_date,
  vh, vv, nbr2, ndmi, ndre, ndvi, gndvi, msavi,
  dry_days, bare_soil_index, valid_pixel_ratio,
  temperature_c_mean, precipitation_mm_3d, precipitation_mm_7d, precipitation_mm_30d
)
VALUES (
  gen_random_uuid(),
  $1,
  $2,
  $3, $4, $5, $6, $7,
  $8, $9, $10,
  $11, $12, $13,
  $14, $15,
  $16, $17
)
ON CONFLICT (tile_id, observation_date) DO UPDATE SET
  vh = EXCLUDED.vh, vv = EXCLUDED.vv, nbr2 = EXCLUDED.nbr2,
  ndmi = EXCLUDED.ndmi, ndre = EXCLUDED.ndre, ndvi = EXCLUDED.ndvi,
  gndvi = EXCLUDED.gndvi, msavi = EXCLUDED.msavi,
  dry_days = EXCLUDED.dry_days, bare_soil_index = EXCLUDED.bare_soil_index,
  valid_pixel_ratio = EXCLUDED.valid_pixel_ratio,
  temperature_c_mean = EXCLUDED.temperature_c_mean,
  precipitation_mm_3d = EXCLUDED.precipitation_mm_3d,
  precipitation_mm_7d = EXCLUDED.precipitation_mm_7d,
  precipitation_mm_30d = EXCLUDED.precipitation_mm_30d
RETURNING id
`

type InsertTileTimeseriesParams struct {
	TileID             uuid.UUID          `json:"tile_id"`
	ObservationDate    pgtype.Timestamptz `json:"observation_date"`
	Vh                 pgtype.Numeric     `json:"vh"`
	Vv                 pgtype.Numeric     `json:"vv"`
	Nbr2               pgtype.Numeric     `json:"nbr2"`
	Ndmi               pgtype.Numeric     `json:"ndmi"`
	Ndre               pgtype.Numeric     `json:"ndre"`
	Ndvi               pgtype.Numeric     `json:"ndvi"`
	Gndvi              pgtype.Numeric     `json:"gndvi"`
	Msavi              pgtype.Numeric     `json:"msavi"`
	DryDays            pgtype.Int4        `json:"dry_days"`
	BareSoilIndex      pgtype.Numeric     `json:"bare_soil_index"`
	ValidPixelRatio    pgtype.Numeric     `json:"valid_pixel_ratio"`
	TemperatureCMean   pgtype.Numeric     `json:"temperature_c_mean"`
	PrecipitationMm3d  pgtype.Numeric     `json:"precipitation_mm_3d"`
	PrecipitationMm7d  pgtype.Numeric     `json:"precipitation_mm_7d"`
	PrecipitationMm30d pgtype.Numeric     `json:"precipitation_mm_30d"`
}

func (q *Queries) InsertTileTimeseries(ctx context.Context, arg InsertTileTimeseriesParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTileTimeseries,
		arg.TileID,
		arg.ObservationDate,
		arg.Vh,
		arg.Vv,
		arg.Nbr2,
		arg.Ndmi,
		arg.Ndre,
		arg.Ndvi,
		arg.Gndvi,
		arg.Msavi,
		arg.DryDays,
		arg.BareSoilIndex,
		arg.ValidPixelRatio,
		arg.TemperatureCMean,
		arg.PrecipitationMm3d,
		arg.PrecipitationMm7d,
		arg.PrecipitationMm30d,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listTileTimeseriesByTileID = `-- name: ListTileTimeseriesByTileID :many
SELECT id, tile_id, observation_date,
  vh, vv, nbr2, ndmi, ndre, ndvi, gndvi, msavi,
  dry_days, bare_soil_index, valid_pixel_ratio,
  temperature_c_mean, precipitation_mm_3d, precipitation_mm_7d, precipitation_mm_30d,
  stress_index, created_at
FROM tile_timeseries
WHERE tile_id = $1
ORDER BY observation_date DESC
LIMIT 50
`

func (q *Queries) ListTileTimeseriesByTileID(ctx context.Context, tileID uuid.UUID) ([]TileTimeseries, error) {
	rows, err := q.db.Query(ctx, listTileTimeseriesByTileID, tileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TileTimeseries
	for rows.Next() {
		var i TileTimeseries
		if err := rows.Scan(
			&i.ID,
			&i.TileID,
			&i.ObservationDate,
			&i.Vh,
			&i.Vv,
			&i.Nbr2,
			&i.Ndmi,
			&i.Ndre,
			&i.Ndvi,
			&i.Gndvi,
			&i.Msavi,
			&i.DryDays,
			&i.BareSoilIndex,
			&i.ValidPixelRatio,
			&i.TemperatureCMean,
			&i.PrecipitationMm3d,
			&i.PrecipitationMm7d,
			&i.PrecipitationMm30d,
			&i.StressIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
