// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tile.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTile = `-- name: CreateTile :one
INSERT INTO tiles (id, field_id, geometry)
VALUES (
  gen_random_uuid(),
  $1,
  ST_GeomFromWKB($2::bytea, 4326)
)
RETURNING id
`

type CreateTileParams struct {
	FieldID     uuid.UUID `json:"field_id"`
	GeometryWkb []byte    `json:"geometry_wkb"`
}

func (q *Queries) CreateTile(ctx context.Context, arg CreateTileParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTile, arg.FieldID, arg.GeometryWkb)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteTilesByFieldID = `-- name: DeleteTilesByFieldID :exec
DELETE FROM tiles
WHERE field_id = $1
`

func (q *Queries) DeleteTilesByFieldID(ctx context.Context, fieldID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTilesByFieldID, fieldID)
	return err
}

const insertTileWithID = `-- name: InsertTileWithID :exec
INSERT INTO tiles (id, field_id, geometry)
VALUES (
  $1,
  $2,
  ST_GeomFromWKB($3::bytea, 4326)
)
`

type InsertTileWithIDParams struct {
	ID          uuid.UUID `json:"id"`
	FieldID     uuid.UUID `json:"field_id"`
	GeometryWkb []byte    `json:"geometry_wkb"`
}

func (q *Queries) InsertTileWithID(ctx context.Context, arg InsertTileWithIDParams) error {
	_, err := q.db.Exec(ctx, insertTileWithID, arg.ID, arg.FieldID, arg.GeometryWkb)
	return err
}

const listTileIDsByFieldID = `-- name: ListTileIDsByFieldID :many
SELECT id
FROM tiles
WHERE field_id = $1
ORDER BY id
`

func (q *Queries) ListTileIDsByFieldID(ctx context.Context, fieldID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTileIDsByFieldID, fieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTilesByFieldID = `-- name: ListTilesByFieldID :many
SELECT id, field_id, geometry
FROM tiles
WHERE field_id = $1
ORDER BY id
`

func (q *Queries) ListTilesByFieldID(ctx context.Context, fieldID uuid.UUID) ([]Tile, error) {
	rows, err := q.db.Query(ctx, listTilesByFieldID, fieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tile
	for rows.Next() {
		var i Tile
		if err := rows.Scan(&i.ID, &i.FieldID, &i.Geometry); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTilesGeoJSONByFieldID = `-- name: ListTilesGeoJSONByFieldID :many
SELECT id, ST_AsGeoJSON(geometry)::json AS geometry_json
FROM tiles
WHERE field_id = $1
ORDER BY id
`

type ListTilesGeoJSONByFieldIDRow struct {
	ID           uuid.UUID `json:"id"`
	GeometryJson []byte    `json:"geometry_json"`
}

func (q *Queries) ListTilesGeoJSONByFieldID(ctx context.Context, fieldID uuid.UUID) ([]ListTilesGeoJSONByFieldIDRow, error) {
	rows, err := q.db.Query(ctx, listTilesGeoJSONByFieldID, fieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTilesGeoJSONByFieldIDRow
	for rows.Next() {
		var i ListTilesGeoJSONByFieldIDRow
		if err := rows.Scan(&i.ID, &i.GeometryJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
