// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_preferences.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, locale, timezone, avatar_url, units_system, date_format, fields_default_year, updated_at
FROM user_preferences
WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID uuid.UUID) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Locale,
		&i.Timezone,
		&i.AvatarUrl,
		&i.UnitsSystem,
		&i.DateFormat,
		&i.FieldsDefaultYear,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :exec
INSERT INTO user_preferences (
  user_id, locale, timezone, avatar_url, units_system, date_format, fields_default_year, updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  now()
)
ON CONFLICT (user_id) DO UPDATE SET
  locale = EXCLUDED.locale,
  timezone = EXCLUDED.timezone,
  avatar_url = EXCLUDED.avatar_url,
  units_system = EXCLUDED.units_system,
  date_format = EXCLUDED.date_format,
  fields_default_year = EXCLUDED.fields_default_year,
  updated_at = now()
`

type UpsertUserPreferencesParams struct {
	UserID            uuid.UUID   `json:"user_id"`
	Locale            string      `json:"locale"`
	Timezone          string      `json:"timezone"`
	AvatarUrl         pgtype.Text `json:"avatar_url"`
	UnitsSystem       string      `json:"units_system"`
	DateFormat        string      `json:"date_format"`
	FieldsDefaultYear pgtype.Int4 `json:"fields_default_year"`
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, upsertUserPreferences,
		arg.UserID,
		arg.Locale,
		arg.Timezone,
		arg.AvatarUrl,
		arg.UnitsSystem,
		arg.DateFormat,
		arg.FieldsDefaultYear,
	)
	return err
}
